### ISSUE TITLE
tags are not been generated

### ISSUE THREAD

**Issue by dyaacov** [americanexpress/react-seo#22]
Hi,

I'm trying to use latest version of SEO, but I don't get the tags in my html
I do see the tab title changing but view source does not show the title tag + when I share the link on whatsapp I do not see the title

here is my code:

<SEO
        title={addr}
        description={addr}
        siteUrl={window.location.href}
        image={{
          src: 'https://myurl/images/sold-logo.png'
        }}
      />`
`

**Comment by jgolden17** [comment]
Can you share the markup that is generated?

**Comment by dyaacov** [comment]
its a single page application so the markup is the react standard markup - html that links to main.js

1. The tab title do change

My ContactUs component looks like that:

```
return (
    <Panel title="צור קשר">
      <SEO
        title="סולד טכנולוגיות - צור קשר"
        description="צור קשר"
        siteUrl={window.location.href}
      />
```


When I use google dev tools to inspect, I do see the generated meta tags

```
<title>צור קשר</title>
<meta name="description" content="צור קשר" data-react-helmet="true">
```


 but when I share the link via whatsapp/facebook I get some old default title.

Is there a cache on whatsapp/facebook? how can I refresh it?

Thanks
Dekel

**Comment by jgolden17** [comment]
You might try triggering a new crawl with Facebook debugger https://developers.facebook.com/tools/debug/

**Comment by dyaacov** [comment]
Cool!

According to the debugger, og:description and og:title are missing
BUT I do see it when I inspect the page via google dev tool bar.

[image: image.png]

**Comment by dyaacov** [comment]
Anyone?

**Comment by infoxicator** [comment]
Hey @dyaacov if you can see the tags when inspecting the element but when you go to view source you can't see them it might be to do with your app not doing server side rendering. I think when React runs in the client it renders the additional tags as a SPA would do, but if you are not doing server side rendering, the tags will not be visible in the original html before the javascript runs, hope that helps? 👍

**Comment by dyaacov** [comment]
Hi,

I knew that... I thought react-seo brings some new solution to the SPA app

thanks anyway
Dekel
