### ISSUE TITLE
Add support for node 14.x

### ISSUE THREAD

**Issue by jgolden17** [americanexpress/react-seo#35]

**Comment by jgolden17** [comment]
This effort should include updating the workflows to include testing against 14.x

**Comment by Erik-orange** [comment]
I see this issue has been deemed stale, I'd like to take a stab at it.

**Comment by nellyk** [comment]
@Erik-orange  please feel free to pick up this issue, if you have any questions please let us know

**Comment by Erik-orange** [comment]
@nellyk I created a PR for my fix but it seems to be hung up waiting for status to be reported for Node 10.x and Node 12.x
Travis CI has passed and I've signed the license agreement. Also ran the test locally and they passed. Any tips would be greatly appreciated.

**Comment by nellyk** [comment]
@Erik-orange  i've resolved that for you. Thank you for contribution

**Comment by Erik-orange** [comment]
@nellyk Thanks, I see that it requires 2 approvals to be merged, 1 of which you've already provided. I don't see a way to request additional reviewers.

**Comment by nellyk** [comment]
Our team is aware of the pull request and will review it, thank you

**Comment by nellyk** [comment]
this has now been merged. Thank you for your contribution

**Comment by Erik-orange** [comment]
@nellyk Thank you for all the help along the process. I look forward to contributing some more in the near future!
